# This file should be copied to .streamlit/config.toml in prod
# Additionally, create a .streamlit/secrets.toml file with permissions 0600 to contain keys

[server]
port = 8507
baseUrlPath = "/pedsrvu"

# Don't launch browser on startup
headless = true

[client]
# Remove top right menu
toolbarMode = "minimal"

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[browser]
gatherUsageStats = false