import streamlit as st
from . import configs, data, ui, figs
from ...model import source_data


def dept_page(src_data: source_data.SourceData, route_id: str):
    """
    Show department specific Streamlit page
    """
    # Get base configuration for given department. route_id is generated by
    # route.py based on the "dept" URL query param.
    dept_config = configs.config_from_route(route_id)
    if dept_config is None:
        return st.write("Dashboard for this department is not yet available.")

    # Get sidebar user settings. Settings embedded in the content handled by ui module.
    user_settings = ui.show_settings(dept_config, src_data)

    # Process the source data by filtering and generating the specifc metrics displayed in the UI
    dept_data = data.process(dept_config, user_settings, src_data)

    # Show main content
    ui.show(dept_config, user_settings, dept_data)
